import type { ButtonHTMLAttributes, InputHTMLAttributes, ReactNode, SelectHTMLAttributes, TextareaHTMLAttributes } from 'react';

export function Button({ className = '', variant = 'primary', ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'secondary' | 'danger' | 'ghost' }) {
  const styles = { primary: 'bg-brand-900 text-white hover:bg-brand-700', secondary: 'bg-white text-slate-800 border border-slate-300 hover:bg-slate-50', danger: 'bg-red-600 text-white hover:bg-red-700', ghost: 'bg-transparent text-slate-700 hover:bg-slate-100' };
  return <button className={`inline-flex min-h-10 items-center justify-center gap-2 rounded-lg px-4 py-2 text-sm font-semibold transition disabled:cursor-not-allowed disabled:opacity-50 ${styles[variant]} ${className}`} {...props} />;
}
export function Card({ children, className = '' }: { children: ReactNode; className?: string }) { return <section className={`rounded-2xl border border-slate-200 bg-white p-5 shadow-card ${className}`}>{children}</section>; }
export function PageHeader({ title, description, actions }: { title: string; description?: string; actions?: ReactNode }) { return <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-bold text-slate-950">{title}</h1>{description && <p className="mt-1 text-sm text-slate-600">{description}</p>}</div>{actions}</div>; }
export function Field({ label, error, children, required }: { label: string; error?: string; children: ReactNode; required?: boolean }) { return <label className="block"><span className="mb-1.5 block text-sm font-semibold text-slate-700">{label}{required && <span className="text-red-600"> *</span>}</span>{children}{error && <span className="mt-1 block text-sm text-red-600">{error}</span>}</label>; }
const base = 'min-h-11 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-slate-900 placeholder:text-slate-400 focus:border-sky-500';
export const Input = (props: InputHTMLAttributes<HTMLInputElement>) => <input {...props} className={`${base} ${props.className || ''}`} />;
export const Select = (props: SelectHTMLAttributes<HTMLSelectElement>) => <select {...props} className={`${base} ${props.className || ''}`} />;
export const Textarea = (props: TextareaHTMLAttributes<HTMLTextAreaElement>) => <textarea {...props} className={`${base} min-h-24 ${props.className || ''}`} />;
export function Badge({ children, tone = 'blue' }: { children: ReactNode; tone?: 'blue'|'green'|'yellow'|'red'|'gray' }) { const map = { blue:'bg-blue-100 text-blue-800', green:'bg-emerald-100 text-emerald-800', yellow:'bg-amber-100 text-amber-800', red:'bg-red-100 text-red-800', gray:'bg-slate-100 text-slate-700' }; return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${map[tone]}`}>{children}</span>; }
export function EmptyState({ title, description }: { title: string; description: string }) { return <div className="rounded-xl border border-dashed border-slate-300 p-10 text-center"><h3 className="font-semibold text-slate-900">{title}</h3><p className="mt-1 text-sm text-slate-600">{description}</p></div>; }
