-- Sistema CIPTEA - esquema inicial. Execute em um projeto Supabase novo.
create extension if not exists pgcrypto;

create type public.app_role as enum ('administrator','operator','analyst','approver','issuer','auditor','support');
create type public.application_status as enum ('draft','incomplete','awaiting_documents','under_review','pending','approved','rejected','awaiting_issuance','issued','printed','delivered','expired','suspended','cancelled','replaced','reissued');
create type public.card_status as enum ('valid','expired','suspended','cancelled','replaced');

create table public.administrative_units (id uuid primary key default gen_random_uuid(), name text not null, code text not null unique, city text not null, state char(2) not null, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text not null, email text, unit_id uuid references public.administrative_units(id), active boolean not null default true, blocked_at timestamptz, last_access_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.user_roles (user_id uuid not null references public.profiles(id) on delete cascade, role public.app_role not null, unit_id uuid not null references public.administrative_units(id), granted_by uuid references public.profiles(id), created_at timestamptz not null default now(), primary key(user_id,role,unit_id));

create table public.beneficiaries (id uuid primary key default gen_random_uuid(), unit_id uuid not null references public.administrative_units(id), full_name text not null, social_name text, birth_date date not null, sex text not null, cpf text, rg text, sus_number text not null, phone text, email text, zip_code text, address text, city text not null, state char(2) not null, cid text not null, support_level text not null, photo_path text, created_by uuid not null default auth.uid() references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz, constraint sus_number_format check (sus_number ~ '^[0-9 .-]{15,18}$'));
create unique index beneficiaries_cpf_unique on public.beneficiaries(cpf) where cpf is not null and deleted_at is null;
create index beneficiaries_unit_name_idx on public.beneficiaries(unit_id,full_name);

create table public.parentages (id uuid primary key default gen_random_uuid(), beneficiary_id uuid not null references public.beneficiaries(id) on delete cascade, full_name text not null, relationship_type text not null, cpf text, created_at timestamptz not null default now());
create table public.caregivers (id uuid primary key default gen_random_uuid(), beneficiary_id uuid not null references public.beneficiaries(id) on delete cascade, full_name text not null, cpf text, phone text not null, email text, relationship text not null, address text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.emergency_information (id uuid primary key default gen_random_uuid(), beneficiary_id uuid not null unique references public.beneficiaries(id) on delete cascade, blood_type text, allergies text, continuous_medications text, important_conditions text, other_information text, emergency_contact text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create table public.applications (id uuid primary key default gen_random_uuid(), unit_id uuid not null references public.administrative_units(id), beneficiary_id uuid not null references public.beneficiaries(id), status public.application_status not null default 'draft', requested_at date not null default current_date, issued_at date, expires_at date, card_number text, notes text, created_by uuid not null default auth.uid() references public.profiles(id), approved_by uuid references public.profiles(id), approved_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create unique index applications_card_number_unique on public.applications(card_number) where card_number is not null;
create index applications_status_idx on public.applications(unit_id,status);
create table public.application_documents (id uuid primary key default gen_random_uuid(), application_id uuid not null references public.applications(id) on delete cascade, category text not null, storage_path text not null, mime_type text not null, size_bytes bigint not null, analysis_status text not null default 'pending', analysis_note text, analyzed_by uuid references public.profiles(id), analyzed_at timestamptz, version integer not null default 1, created_by uuid not null default auth.uid() references public.profiles(id), created_at timestamptz not null default now(), deleted_at timestamptz);
create table public.application_reviews (id uuid primary key default gen_random_uuid(), application_id uuid not null references public.applications(id) on delete cascade, reviewer_id uuid not null default auth.uid() references public.profiles(id), recommendation text not null, notes text, created_at timestamptz not null default now());
create table public.application_status_history (id bigint generated always as identity primary key, application_id uuid not null references public.applications(id), old_status public.application_status, new_status public.application_status not null, reason text, changed_by uuid not null default auth.uid() references public.profiles(id), changed_at timestamptz not null default now());

create table public.card_templates (id uuid primary key default gen_random_uuid(), name text not null, active boolean not null default true, created_by uuid not null default auth.uid() references public.profiles(id), created_at timestamptz not null default now());
create table public.card_template_versions (id uuid primary key default gen_random_uuid(), template_id uuid not null references public.card_templates(id), version integer not null, front_path text not null, back_path text not null, width_mm numeric(8,2) not null default 85.60, height_mm numeric(8,2) not null default 132.50, bleed_mm numeric(8,2) not null default 0, config jsonb not null default '{}'::jsonb, published_at timestamptz, created_by uuid not null default auth.uid() references public.profiles(id), created_at timestamptz not null default now(), unique(template_id,version));
create table public.template_fields (id uuid primary key default gen_random_uuid(), template_version_id uuid not null references public.card_template_versions(id) on delete cascade, technical_name text not null, label text not null, side text not null check(side in('front','back')), field_type text not null, x numeric not null, y numeric not null, width numeric not null, height numeric not null, style jsonb not null default '{}'::jsonb, validation jsonb not null default '{}'::jsonb, required boolean not null default false, visible boolean not null default true);

create table public.cards (id uuid primary key default gen_random_uuid(), application_id uuid not null unique references public.applications(id), beneficiary_id uuid not null references public.beneficiaries(id), unit_id uuid not null references public.administrative_units(id), card_number text not null unique, status public.card_status not null default 'valid', current_version integer not null default 1, issued_at date not null, expires_at date not null, created_by uuid not null default auth.uid() references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.card_versions (id uuid primary key default gen_random_uuid(), card_id uuid not null references public.cards(id), version integer not null, template_version_id uuid references public.card_template_versions(id), snapshot jsonb not null, pdf_path text not null, pdf_sha256 text not null, created_by uuid not null default auth.uid() references public.profiles(id), created_at timestamptz not null default now(), unique(card_id,version));
create table public.card_status_history (id bigint generated always as identity primary key, card_id uuid not null references public.cards(id), old_status public.card_status, new_status public.card_status not null, reason text not null, changed_by uuid not null default auth.uid() references public.profiles(id), changed_at timestamptz not null default now());
create table public.verification_credentials (id uuid primary key default gen_random_uuid(), card_id uuid not null references public.cards(id), token_hash text not null unique, public_code text not null unique, active boolean not null default true, revoked_at timestamptz, created_at timestamptz not null default now());
create table public.print_jobs (id uuid primary key default gen_random_uuid(), card_version_id uuid not null references public.card_versions(id), quantity integer not null default 1, printed_by uuid not null default auth.uid() references public.profiles(id), printed_at timestamptz not null default now(), notes text);
create table public.delivery_records (id uuid primary key default gen_random_uuid(), card_id uuid not null references public.cards(id), delivered_to text not null, relationship text, document_reference text, delivered_by uuid not null default auth.uid() references public.profiles(id), delivered_at timestamptz not null default now(), notes text);
create table public.audit_logs (id bigint generated always as identity primary key, user_id uuid, unit_id uuid, action text not null, entity text not null, record_id uuid, old_data jsonb, new_data jsonb, reason text, ip_hash text, created_at timestamptz not null default now());
create table public.system_settings (id uuid primary key default gen_random_uuid(), unit_id uuid not null references public.administrative_units(id), key text not null, value jsonb not null, updated_by uuid not null default auth.uid() references public.profiles(id), updated_at timestamptz not null default now(), unique(unit_id,key));
create table public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id), title text not null, body text not null, read_at timestamptz, created_at timestamptz not null default now());
create table public.card_number_sequences (unit_id uuid not null references public.administrative_units(id), year integer not null, last_value bigint not null default 0, primary key(unit_id,year));

create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
create trigger trg_profiles_updated before update on public.profiles for each row execute function public.set_updated_at();
create trigger trg_beneficiaries_updated before update on public.beneficiaries for each row execute function public.set_updated_at();
create trigger trg_applications_updated before update on public.applications for each row execute function public.set_updated_at();
create trigger trg_cards_updated before update on public.cards for each row execute function public.set_updated_at();

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,full_name,email) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',split_part(new.email,'@',1)),new.email); return new; end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.my_unit_id() returns uuid language sql stable security definer set search_path=public as $$ select unit_id from public.profiles where id=auth.uid() $$;
create or replace function public.has_role(required_role public.app_role) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.user_roles where user_id=auth.uid() and role=required_role and unit_id=public.my_unit_id()) $$;
create or replace function public.get_my_profile() returns table(id uuid,full_name text,email text,unit_id uuid,active boolean,roles public.app_role[]) language sql stable security definer set search_path=public as $$ select p.id,p.full_name,p.email,p.unit_id,p.active,coalesce(array_agg(ur.role) filter(where ur.role is not null),'{}') from public.profiles p left join public.user_roles ur on ur.user_id=p.id where p.id=auth.uid() group by p.id $$;


alter table public.beneficiaries alter column unit_id set default public.my_unit_id();
alter table public.applications alter column unit_id set default public.my_unit_id();

create or replace function public.audit_row_change() returns trigger language plpgsql security definer set search_path=public as $$
declare v_old jsonb;v_new jsonb;v_id uuid;v_unit uuid;
begin
  v_old:=case when tg_op='INSERT' then null else to_jsonb(old) end;
  v_new:=case when tg_op='DELETE' then null else to_jsonb(new) end;
  if tg_table_name='beneficiaries' then
    v_old:=v_old-'sus_number'-'cid'-'photo_path'-'cpf'-'rg';
    v_new:=v_new-'sus_number'-'cid'-'photo_path'-'cpf'-'rg';
  end if;
  v_id:=coalesce((v_new->>'id')::uuid,(v_old->>'id')::uuid);
  v_unit:=coalesce(nullif(v_new->>'unit_id','')::uuid,nullif(v_old->>'unit_id','')::uuid,public.my_unit_id());
  insert into public.audit_logs(user_id,unit_id,action,entity,record_id,old_data,new_data)
  values(auth.uid(),v_unit,tg_op,tg_table_name,v_id,v_old,v_new);
  return coalesce(new,old);
end $$;
create trigger audit_beneficiaries after insert or update or delete on public.beneficiaries for each row execute function public.audit_row_change();
create trigger audit_applications after insert or update or delete on public.applications for each row execute function public.audit_row_change();
create trigger audit_cards after insert or update or delete on public.cards for each row execute function public.audit_row_change();
create trigger audit_templates after insert or update or delete on public.card_template_versions for each row execute function public.audit_row_change();

create or replace function public.generate_card_number(p_unit_id uuid) returns text language plpgsql security definer set search_path=public as $$ declare v_year int:=extract(year from current_date);v_seq bigint;v_code text;begin if not(public.has_role('issuer') or public.has_role('administrator')) then raise exception 'Acesso negado';end if;insert into public.card_number_sequences(unit_id,year,last_value) values(p_unit_id,v_year,1) on conflict(unit_id,year) do update set last_value=public.card_number_sequences.last_value+1 returning last_value into v_seq;select code into v_code from public.administrative_units where id=p_unit_id;return format('CIPTEA-%s-%s-%s',v_code,v_year,lpad(v_seq::text,6,'0'));end $$;

create or replace function public.transition_application_status(p_application_id uuid,p_new_status public.application_status,p_reason text default null) returns public.applications language plpgsql security definer set search_path=public as $$ declare a public.applications;v_old public.application_status;begin select * into a from public.applications where id=p_application_id for update;if not found then raise exception 'Solicitação não encontrada';end if;if a.unit_id<>public.my_unit_id() and not public.has_role('administrator') then raise exception 'Acesso negado';end if;if p_new_status='approved' and not(public.has_role('approver') or public.has_role('administrator')) then raise exception 'Somente aprovador pode aprovar';end if;if p_new_status='rejected' and not(public.has_role('approver') or public.has_role('administrator')) then raise exception 'Somente aprovador pode reprovar';end if;if a.created_by=auth.uid() and p_new_status='approved' and not public.has_role('administrator') then raise exception 'Não é permitido aprovar a própria solicitação';end if;v_old:=a.status;update public.applications set status=p_new_status,approved_by=case when p_new_status='approved' then auth.uid() else approved_by end,approved_at=case when p_new_status='approved' then now() else approved_at end where id=p_application_id returning * into a;insert into public.application_status_history(application_id,old_status,new_status,reason) values(p_application_id,v_old,p_new_status,p_reason);return a;end $$;
