alter table public.administrative_units enable row level security;alter table public.profiles enable row level security;alter table public.user_roles enable row level security;alter table public.beneficiaries enable row level security;alter table public.parentages enable row level security;alter table public.caregivers enable row level security;alter table public.emergency_information enable row level security;alter table public.applications enable row level security;alter table public.application_documents enable row level security;alter table public.application_reviews enable row level security;alter table public.application_status_history enable row level security;alter table public.card_templates enable row level security;alter table public.card_template_versions enable row level security;alter table public.template_fields enable row level security;alter table public.cards enable row level security;alter table public.card_versions enable row level security;alter table public.card_status_history enable row level security;alter table public.verification_credentials enable row level security;alter table public.print_jobs enable row level security;alter table public.delivery_records enable row level security;alter table public.audit_logs enable row level security;alter table public.system_settings enable row level security;alter table public.notifications enable row level security;alter table public.card_number_sequences enable row level security;

create policy units_read on public.administrative_units for select to authenticated using(active or public.has_role('administrator'));
create policy profiles_self_read on public.profiles for select to authenticated using(id=auth.uid() or public.has_role('administrator'));
create policy profiles_admin_write on public.profiles for all to authenticated using(public.has_role('administrator')) with check(public.has_role('administrator'));
create policy roles_admin_only on public.user_roles for all to authenticated using(public.has_role('administrator')) with check(public.has_role('administrator'));

create policy beneficiaries_read on public.beneficiaries for select to authenticated using(unit_id=public.my_unit_id() and (public.has_role('administrator') or public.has_role('operator') or public.has_role('analyst') or public.has_role('approver') or public.has_role('issuer') or public.has_role('auditor') or public.has_role('support')));
create policy beneficiaries_insert on public.beneficiaries for insert to authenticated with check(unit_id=public.my_unit_id() and (public.has_role('administrator') or public.has_role('operator')));
create policy beneficiaries_update on public.beneficiaries for update to authenticated using(unit_id=public.my_unit_id() and (public.has_role('administrator') or public.has_role('operator'))) with check(unit_id=public.my_unit_id());

create policy related_parentages on public.parentages for all to authenticated using(exists(select 1 from public.beneficiaries b where b.id=beneficiary_id and b.unit_id=public.my_unit_id())) with check(exists(select 1 from public.beneficiaries b where b.id=beneficiary_id and b.unit_id=public.my_unit_id()));
create policy related_caregivers on public.caregivers for all to authenticated using(exists(select 1 from public.beneficiaries b where b.id=beneficiary_id and b.unit_id=public.my_unit_id())) with check(exists(select 1 from public.beneficiaries b where b.id=beneficiary_id and b.unit_id=public.my_unit_id()));
create policy related_emergency on public.emergency_information for all to authenticated using(exists(select 1 from public.beneficiaries b where b.id=beneficiary_id and b.unit_id=public.my_unit_id()) and not public.has_role('support')) with check(exists(select 1 from public.beneficiaries b where b.id=beneficiary_id and b.unit_id=public.my_unit_id()));

create policy applications_read on public.applications for select to authenticated using(unit_id=public.my_unit_id());
create policy applications_insert on public.applications for insert to authenticated with check(unit_id=public.my_unit_id() and (public.has_role('operator') or public.has_role('administrator')));
create policy applications_update on public.applications for update to authenticated using(unit_id=public.my_unit_id() and not public.has_role('auditor')) with check(unit_id=public.my_unit_id());
create policy application_documents_access on public.application_documents for all to authenticated using(exists(select 1 from public.applications a where a.id=application_id and a.unit_id=public.my_unit_id()) and not public.has_role('support')) with check(exists(select 1 from public.applications a where a.id=application_id and a.unit_id=public.my_unit_id()));
create policy reviews_access on public.application_reviews for select to authenticated using(exists(select 1 from public.applications a where a.id=application_id and a.unit_id=public.my_unit_id()));
create policy reviews_insert on public.application_reviews for insert to authenticated with check(public.has_role('analyst') or public.has_role('approver') or public.has_role('administrator'));
create policy application_history_read on public.application_status_history for select to authenticated using(exists(select 1 from public.applications a where a.id=application_id and a.unit_id=public.my_unit_id()));

create policy templates_read on public.card_templates for select to authenticated using(true);create policy templates_admin on public.card_templates for all to authenticated using(public.has_role('administrator')) with check(public.has_role('administrator'));
create policy template_versions_read on public.card_template_versions for select to authenticated using(true);create policy template_versions_admin on public.card_template_versions for all to authenticated using(public.has_role('administrator')) with check(public.has_role('administrator'));
create policy template_fields_read on public.template_fields for select to authenticated using(true);create policy template_fields_admin on public.template_fields for all to authenticated using(public.has_role('administrator')) with check(public.has_role('administrator'));
create policy cards_read on public.cards for select to authenticated using(unit_id=public.my_unit_id());create policy cards_issuer_write on public.cards for all to authenticated using(public.has_role('issuer') or public.has_role('administrator')) with check(unit_id=public.my_unit_id());
create policy card_versions_read on public.card_versions for select to authenticated using(exists(select 1 from public.cards c where c.id=card_id and c.unit_id=public.my_unit_id()));
create policy card_status_read on public.card_status_history for select to authenticated using(exists(select 1 from public.cards c where c.id=card_id and c.unit_id=public.my_unit_id()));
create policy verification_none on public.verification_credentials for all to authenticated using(false) with check(false);
create policy print_access on public.print_jobs for all to authenticated using(public.has_role('issuer') or public.has_role('administrator')) with check(public.has_role('issuer') or public.has_role('administrator'));
create policy delivery_access on public.delivery_records for all to authenticated using(exists(select 1 from public.cards c where c.id=card_id and c.unit_id=public.my_unit_id())) with check(exists(select 1 from public.cards c where c.id=card_id and c.unit_id=public.my_unit_id()));
create policy audit_read on public.audit_logs for select to authenticated using(public.has_role('administrator') or public.has_role('auditor'));-- sem políticas de update/delete
create policy settings_read on public.system_settings for select to authenticated using(unit_id=public.my_unit_id());create policy settings_admin on public.system_settings for all to authenticated using(public.has_role('administrator')) with check(unit_id=public.my_unit_id());
create policy notifications_self on public.notifications for select to authenticated using(user_id=auth.uid());create policy notifications_update on public.notifications for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
